version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://av:av@db:5432/avautorun
      NODE_ENV: development
      PORT: 3000
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s

  worker:
    build:
      context: ./services/worker
      dockerfile: Dockerfile.dev
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://av:av@db:5432/avautorun
      NODE_ENV: development
    depends_on:
      - redis
    volumes:
      - ./services/worker:/app
      - /app/node_modules

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: av
      POSTGRES_PASSWORD: av
      POSTGRES_DB: avautorun
    ports: ["5432:5432"]
    volumes: [pg:/var/lib/postgresql/data]

volumes:
  pg:

